name: Webhost Release Unstable

on: 
  push:
    branches: [ dev ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Updating base image
        run: sudo apt update

      - name: Installing zip 
        run: sudo apt install zip -y

      - name: Installing Node
        run: sudo apt install nodejs npm -y
      
      - name: Install PHP dependencies
        uses: php-actions/composer@v5
        with:
          dev: no
          php_version: 7.4
      
      - name: Install Node depencencies
        run: npm install

      - name: Zipping the folder
        run: |
          cd ..
          zip -r unstable_webhost_ready.zip biskuit/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: unstable
          title: Unstable build
          files: unstable_webhost_ready.zip